package rules;

import org.apache.camel.CamelContext;
import org.apache.camel.ProducerTemplate;
import java.util.ArrayList;
import org.acme.model.Person

//global org.acme.test.CamelHelper camelHelper;
global org.acme.model.Person person;
global java.util.ArrayList persons;

rule "Demo"
    when
      Person()
    then
      System.out.println("[ Fired: " + drools.getRule().getName() + " ]");
      System.out.println("[ Person[0] : " + persons.get(0) + " ]");
      System.out.println("[ Person name : " + person.getName() + " ]");

      //System.out.println("[Camel Helper : " + camelHelper + "]");
      //camelHelper.sendMessage("Hello World");
end
