package rules;

import org.apache.camel.CamelContext;
import org.apache.camel.ProducerTemplate;
import java.util.ArrayList;
import org.acme.model.Person

global org.acme.test.CamelHelper camelHelper;
global java.util.ArrayList list;

rule "Demo"
    when
      Person()
    then
      System.out.println("[ Fired: " + drools.getRule().getName() + " ]");
      System.out.println("[Camel Helper : " + camelHelper + "]");
      //camelHelper.sendMessage("Hello World");
end
